### ISSUE TITLE
error

### ISSUE THREAD

**Issue by somiyaa** [harshitkgupta/Twitter-Sentiment-Analysis#1]
hello harshit

i am getting the following error:

D:\Twitter-Sentiment-Analysis-master\venv\Scripts\python.exe D:/Twitter-Sentiment-Analysis-master/trainSentiment.py
Traceback (most recent call last):
  File "D:/Twitter-Sentiment-Analysis-master/trainSentiment.py", line 34, in <module>
    allFeaturesList = getAllFeaturesList()
  File "D:\Twitter-Sentiment-Analysis-master\commonUtils.py", line 92, in getAllFeaturesList
    allFeaturesList = pickle.load(open(FeaturesListPkl,'rb'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 5: ordinal not in range(128)

i changed 'rb' to 'r' in the following line.
allFeaturesList = pickle.load(open(FeaturesListPkl,'rb'))

error: 
Traceback (most recent call last):
  File "D:/Twitter-Sentiment-Analysis-master/trainSentiment.py", line 34, in <module>
    allFeaturesList = getAllFeaturesList()
  File "D:\Twitter-Sentiment-Analysis-master\commonUtils.py", line 92, in getAllFeaturesList
    allFeaturesList = pickle.load(open(FeaturesListPkl,'r'))
TypeError: a bytes-like object is required, not 'str'

how to fix this error? this error is coming for all the pickle files.
please help...

**Comment by somiyaa** [comment]
previous error resolved.
but now i am getting another error:


print 'precision', (pos_precision + neg_precision) / 2
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

kindly reply.
